### ISSUE TITLE
local development environment

### ISSUE THREAD

**Issue by BryanChrisBrown** [playcanvas/super-splat#11]
I've cloned the repo and installed the submodules and packages, however can't seem to get the project to run locally, running npm run develop returns a 404. 

npm run build seems to work, but it's unclear how to setup the development environment currently, any tips here? 

this would be great to add to the readme 🙏🏻 

Thanks!

**Comment by BryanChrisBrown** [comment]
embarrassingly enough this was because my existing localhost port:3000 was already being used 😅

**Comment by slimbuck** [comment]
Oh great, I was about to suggest running `git submodule update --init` :)
