### ISSUE TITLE
Poly-cam file not loading

### ISSUE THREAD

**Issue by rowild** [playcanvas/super-splat#13]
Does Super Splat support poly.cam? I couldn't get my file to work (see error message in attached screenshot).
This is my file: https://dl.rowild.at/point_cloud.ply

![Screenshot 2023-11-05 at 07 27 04](https://github.com/playcanvas/super-splat/assets/213803/08edb828-646a-491e-851a-58e835ec9f5d)

**Comment by slimbuck** [comment]
HI, Polycam definitely works - I used it to create multiple scenes.

Make sure you select "Create a Gaussian Splat".

<img width="552" alt="Screenshot 2023-11-06 at 08 53 25" src="https://github.com/playcanvas/super-splat/assets/11276292/193d678d-6c98-41dd-82e2-4087ced23004">

If you've done that and it still doesn't work, please attach the file so I can take a look.

Closing, but please reopen if necessary.

**Comment by rowild** [comment]
@slimbuck You are absolutely right, it works! Not sure, what I did wrong before - I think I exported an object created with photogrammetry as point cloud. – Thank you!
