### ISSUE TITLE
Breaks PLY compatibility

### ISSUE THREAD

**Issue by AtlasRedux** [playcanvas/super-splat#14]
Exported PLYs with Super-Splat has broken compatibility. What exactly breaks is way above my knowledge level.
Impossible to open with https://www.unrealengine.com/marketplace/en-US/product/3d-gaussians-plugin for instance.

**Comment by slimbuck** [comment]
Might be worth logging this on the develop's website since I can't test this myself. I suspect the plugin assumes all spherical harmonic data is present. We'll add this option soon!

**Comment by AtlasRedux** [comment]
Would be great, since I can't afford to pay another small fortune for the only plugin that currently supports you in Unreal Engine xD

**Comment by iliesaya** [comment]
it's also broken when trying to import ply with Luma AI plugin for UE5 https://lumaai.notion.site/Luma-Unreal-Engine-Plugin-0-4-8005919d93444c008982346185e933a1#0dea5ebba2e24566b7f622a113b38373

**Comment by slimbuck** [comment]
I'll add an option so user can choose how many bands of SH to load and save(0..4) - though initially the SH will not be used for rendering in the viewport.

**Comment by slimbuck** [comment]
We've released https://github.com/playcanvas/super-splat/releases/tag/v0.10.1 which includes an option to load/save the extra SH data.

Please can you try modifying a scene with option enabled and confirm the resulting files load correctly in the respective plugins?

Thanks!

**Comment by AtlasRedux** [comment]
Unfortunately, that's a no. Does not work.
I don't know if it helps to figure it out, but there is a converter that supports converting to CloudCompare and back to standard 3DGS PLYs again. Might want to look at what it does when going back to 3DGS. https://github.com/francescofugazzi/3dgsconverter

**Comment by AtlasRedux** [comment]
Reposting for notification purposes:
Unfortunately, that's a no. Does not work.
I don't know if it helps to figure it out, but I'm currently using CloudCompare to edit, and there is a converter that supports converting to CloudCompare and back to standard 3DGS PLYs again which seems to work with every single plugin (since it, again, can convert it back into standard 3DGS PLYs).
Might want to look at what they're doing to re-convert it. https://github.com/francescofugazzi/3dgsconverter
EDIT: I can also confirm that that 3dgsconverter now works on PLYs exported with SH setting on! So there is a step missing, but the information needed for conversion is there.
EDIT 2: Apparently, it works to convert it without SH as well. I could have sworn I did a test on this before and the conversion failed...

**Comment by AtlasRedux** [comment]
Edited previous comment due to misinformation, converter does NOT work with SuperSplat, I must have messed up my workflow and gotten my files mixed up.

**Comment by AtlasRedux** [comment]
What a mess of edits and comment deletes I'm doing, sorry. The converter DOES work on SuperSplat (originally made for working with CloudCompare).
So all that needs to be done to open it is:
- Import and export with Super-Splat, with or without SH on.
- Run the generated PLY through 3dgsconverter.
- Open with software or plugin of your choosing. Should work with anything, since 3dgsconverter converts back into completely standard 3DGS PLYs.

No idea what they do that makes it compatible, since all of this is severely out of my league, I just know that it works by testing.
So up to you if you want to check what they are doing to make it 3DGS original compatible and implement a similar feature or suggest using a converter if there are compatibility issues.

**Comment by slimbuck** [comment]
Thanks for the realtime updates @AtlasRedux!

I've just noticed that we're exporting some internal editor data to PLY. Presumably it's the extra data that's confusing the plugins. I'll remove that from the output stream.

**Comment by slimbuck** [comment]
Ok we've updated the editor. Please try again!

**Comment by AtlasRedux** [comment]
Going to need a live version, for some reason I can't get it to work. Even tried making a test web server in case some weirdness doesn't allow for it to work on local file systems...

**Comment by AtlasRedux** [comment]
Going to need a live version or a build guide. Installed NodeJS and did an NPM INSTALL, but I have absolutely no idea what the output remotely even is. I have zero experience with this, and I just see a bunch of folders I have no idea what is for after an NPM INSTALL.

**Comment by AtlasRedux** [comment]
Going to need a live version or a build/use guide. Installed NodeJS and tried figuring out how to build this, but no go. I am very dependant on build- and usage-instructions on github projects, if it's not VS, I don't know it :P

**Comment by slimbuck** [comment]
Sorry I'd published the wrong version. I tested this time and don't see the internal bits exported. Should be all good now 🤞🏼

**Comment by slimbuck** [comment]
(Though you might need to reload the page without cache - ctrl + f5)

**Comment by slimbuck** [comment]
Regarding building of the project, it was made a mess literally today. We're moving the splat rendering code from one project to another and we've not have time to fix the build steps. Sorry!!!

**Comment by slimbuck** [comment]
(welcome to "bleeding" "edge" :D)

**Comment by AtlasRedux** [comment]
There ya go, works like a charm with SH setting on! Guess you can close it now (maybe make a tooltip explaining that it improves compatibility or something to avoid possible future created Issues)

> (welcome to "bleeding" "edge" :D)

Hehe, indeed.

**Comment by slimbuck** [comment]
Awesome thanks for the help!
