### ISSUE TITLE
Volinga Support?

### ISSUE THREAD

**Issue by rowild** [playcanvas/super-splat#15]
From my tests, Volinga files are not yet supported, right? (Being new to all this; I might most likely is understand the difference in format - at the moment I think it is also a point cloud that gets exported...)

(Not sure if this is a place to ask questions. If not, would you please let me know, where the proper place for that is? Thank you!)

**Comment by slimbuck** [comment]
From a quick look, it seems Volinga deals with nerfs which are related, but quite different from gaussian splatting. Unless they also deal with gaussian splatting it'll likely not working SuperSplat.

**Comment by rowild** [comment]
@slimbuck Thank you! I guess I still didn't grasp the difference (and overlaps) of NeRFs and Gaussian Splats... :-(
