### ISSUE TITLE
[Feature Request] Possibility to scale the model

### ISSUE THREAD

**Issue by softyoda** [playcanvas/super-splat#23]
Hi, first of all, thank you for this tool ! Currently, most of my models are way too big (maybe this tool, or my alignment) but my scans are one or two order of magnitude too big.

Would it be possible to show a grid that would show scale (like the grid can be 200cm by default but maybe editable via slider) 
![image](https://github.com/playcanvas/super-splat/assets/13988751/a3551b91-8c95-410c-95b2-d91f5f9e392e)

Something like that could be useful : 
![image](https://github.com/playcanvas/super-splat/assets/13988751/7c524b19-e0b5-47dc-bf6c-02e35abd8df7)
That way I move the scene center and set scale more easily.

**Comment by slimbuck** [comment]
Hi @softyoda,

We've added uniform scene scale in #31. Not exactly sure when a grid will be added, but we'll keep open this issue so we don't forget about it.

Thanks!

**Comment by slimbuck** [comment]
done in #64
