### ISSUE TITLE
file loading failure

### ISSUE THREAD

**Issue by msken** [playcanvas/super-splat#41]
I made a ply file by training Gaussian Splatting on Colab:
https://colab.research.google.com/github/camenduru/gaussian-splatting-colab/blob/main/gaussian_splatting_colab.ipynb
I downloaded points3D.ply and tried to browse it by super-splat.
When I tried to load the file, it failed with the following message:

TypeError: Cannot read properties of undefined (reading '0')

How can I fix this?

**Comment by slimbuck** [comment]
Hi @msken ,

This message indicates the PLY file does not contain all the gaussian splat data that super-splat expects.

We should definitely update the message to make more sense.

Are there any other PLY output files from the training? It's likely this PLY file contains just points and colors. super-splat expects a PLY file containing sizes, scales, quaternions etc.

Thanks!

**Comment by msken** [comment]
Hello,

I found the output file named point_cloud.ply, which worked fine with super-splat.

Great thanks!
