### ISSUE TITLE
RangeError. Out of memory

### ISSUE THREAD

**Issue by a7345678** [playcanvas/super-splat#42]
The error "RangeError. Out of memory" occurs when attempting to load a 1.4GB PLY file in the Safari or Chrome environment on iOS. This error indicates that there is not enough available memory to handle the file.
![IMG_3404 PNG](https://github.com/playcanvas/super-splat/assets/4329401/e4be1a77-456f-47c8-b3aa-d3edb588b884)

**Comment by slimbuck** [comment]
Actually can I also ask, which browser and device are you using? Thanks

**Comment by a7345678** [comment]
> Hi @a7345678,
> 
> Under the IMPORT options there is a "Load all PLY data" tick box. If you disable that checkbox before loading the PLY, then only the required bits will be loaded from the file.
> 
> Give this a try as it should use less than half the amount of memory.
> 
> Thanks!

I was disabled "Load all PLY data" tick box, The problem still exists

**Comment by a7345678** [comment]
Here's another piece of information: Xiaomi's Android device can run normally.

**Comment by a7345678** [comment]
Thank you for your patient answer.

**Comment by slimbuck** [comment]
Closing.
