### ISSUE TITLE
can't find 'f_rest' properties

### ISSUE THREAD

**Issue by Jing1Ling** [playcanvas/super-splat#73]
Thanks for your great work. 
I read the ply file's properties like this:
```
from plyfile import PlyData
plydata2 = PlyData.read('path/to/plyfile')
print(plydata1.elements[0])
```
I found that the ply file exported from super-splat only output the following information:
```
property float x
property float y
property float z
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
```
Compared with the format saved by 3DGS, there seem to be 45 properties starting with 'f_rest' missing. Is this caused by the way PlyData reads files? How should I find the 'f_rest' information?

**Comment by slimbuck** [comment]
Hi @Jing1Ling,

The `f_rest` properties contain the spherical harmonics data.

By default SuperSplat reads and writes this data. Can you explain what you're doing when the data goes missing?

Thanks!
